With-the-Ranks/Spoke

- libs/gql-schema/organization-settings.ts
- libs/spoke-codegen/src/graphql/general-settings.graphql
- libs/spoke-codegen/src/graphql/spoke-context.graphql
- src/components/MessageLengthInfo.tsx
- src/components/ScriptEditor.tsx
- src/components/forms/GSScriptField.jsx
- src/components/forms/GSScriptOptionsField.jsx
- src/containers/Settings/components/General.jsx
- src/containers/Settings/components/MessageSendingSettingsCard.tsx
- src/lib/charset-utils.ts
- src/lib/scripts.ts
- src/schema.graphql
- src/server/api/lib/assemble-numbers.ts
- src/server/api/organization-settings.ts
- src/server/organization-settings.spec.ts
This adds an organization setting to support the automatic conversion of long SMS messages to MMS.
Closes #1 
> feat: support sending mms without media

- src/server/api/lib/assemble-numbers.ts
This fetches the default for the  org feature `maxSmsSegmentLength` correctly when the feature is not set explicitly
Fix for #2 
> fix(mms): get feature for max sms segment length

- package.json
- yarn.lock
This upgrades to the latest knex version
[`updateFrom`](https://knexjs.org/guide/query-builder.html#updatefrom) looks useful and was added in [v.2.5](https://knexjs.org/changelog.html#_2-5-0-08-july-2023)
N/A
> chore(knex): upgrade to v2.5.1

- libs/gql-schema/user.ts
- libs/spoke-codegen/src/graphql/session.graphql
- src/containers/Home/components/OrganizationList.tsx
- src/schema.graphql
- src/server/api/user.js
This hides inactive orgs on the "select your organization" screen seen when initially logging in
User feedback that this list tends to be very long for instances that have a lot of inactive orgs
> feat: hide inactive orgs on select org screen

- src/components/Links/IncludeImageDocLink.tsx
- src/components/Links/LinkInNewTab.tsx
- src/components/ScriptEditor.tsx
- src/containers/Settings/components/MessageSendingSettingsCard.tsx
This changes relevant links to point to this article: https://withtheranks.com/docs/spoke/for-spoke-admins/include-an-image-in-a-message
Replacing dead link
> fix: use wtr mms doc link

- src/server/tasks/export-campaign.ts
This materializes campaign contacts while preparing exports, to resolve an issue on some instances with query planning in production
See production issue reported here https://withtheranks.slack.com/archives/C0694QK8A3X/p1723067594475649?thread_ts=1723062179.129459&cid=C0694QK8A3X
The code change has been tested locally, and the expected query output has been tested on the production instance to confirm it avoids the query planning issue
> fix(exports): materialize campaign contacts

- src/server/tasks/export-campaign.ts
This fixes the query edit from #39 
The name `materialized_contacts` wasn't updated in the subsequent CTE
> fix(exports): use name of materialized cte

- src/server/tasks/export-campaign.ts
This reverts commit 909db41f1e24a16e307db6b773835c6f39fec140.
Follow up to #39 after repacking the postgres table
N/A
> Revert "fix(exports): materialize campaign contacts (#39)"

- src/server/api/lib/send-message.ts
This updates message sending so that the behavior of updating `campaign_contact.message_status` reflects the most common interpretation of how this should work by admins:
1. After an initial message is sent (the previous `message_status` is `needsMessage`), the status should be updated to `messaged`
2. Any other time a Spoke user sends a message, the status should be updated to "active conversation" (`convo`)
Edit: It's possible to send a message to a contact marked as `messaged` via Message Review - in this case we want to keep the `messaged` status
See context for bug find here: https://withtheranks.slack.com/archives/C01L3B18S10/p1723131234467449?thread_ts=1723060316.173739&cid=C01L3B18S10
> fix: only mark contact as messaged after initial

- src/server/tasks/chunk-tasks/export-campaign/index.ts
This simplifies the calculation for how close to completion the filtered contacts export is:
The relevant code from [`processChunks`](https://github.com/With-the-Ranks/Spoke/blob/096ad161468795080fb7d2bab53544a060b9e9e6/src/server/tasks/chunk-tasks/utils.ts#L110):
```typescript
const newStatus =
Math.round((processed / contactsCount / statusDivider) * 100) +
statusOffset;
await helpers.updateStatus(newStatus);
```
Previously, for the filtered contacts export, this would look like:
```typescript
const newStatus =
Math.round((processed / contactsCount / 4) * 100) + 75;
await helpers.updateStatus(newStatus);
```
Now instead, this is simplified to:
```typescript
const newStatus =
Math.round((processed / contactsCount) * 100)
await helpers.updateStatus(newStatus);
```
Makes this section of …
> chore: simplify calculation of filtered contacts task status

- src/server/mail.ts
- src/server/tasks/chunk-tasks/mark-second-pass/mark-second-pass.spec.ts
- src/server/tasks/chunk-tasks/utils.ts
This adds a test suite for all mark second pass functionality
Follow up to #46 
Tests added in this PR
> test: add test suite for mark second pass

- src/containers/AdminCampaignEdit/sections/CampaignContactsForm/components/ConfigureColumnMappingDialog.tsx
This fixes an issue where mapped columns would be created as 'Create as "value"' instead of the value
We encountered this issue during a demo
> fix(column mapping): remove create as from custom field value

- src/server/api/lib/send-message.ts
This adds an await statement when calling `sendMessage` for a specific service type
Discovered while working on #6 Not all services are written in TS, so type checking around this isn't great
Allows tests from #6 to pass
> fix(send-message): await service method

- src/config.js
- src/server/api/lib/send-message.ts
This removes references to Bernie SMS 🥲 
Trollbot is built into Spoke, and we should prefer building our own sweeping system into Spoke if the Bernie SMS feature set is useful for users
N/A
> chore: remove bernie sms references

- src/containers/UserMenu/index.tsx
This renames "teams" to organizations in the user menu
Organization specific teams are a thing in our fork of Spoke, so the use of the word "Teams" here is confusing
N/A
> chore(user menu): rename teams to organizations

- .eslintrc.js
- package.json
- yarn.lock
This enables linting for json files
PRs that edit json files (ex. #50 #52 ) are currently failing to pass linting. In CI/CD we're using `$ prettier --check './**/*.{js,jsx,ts,tsx,css,md,json}' --config ./.prettierrc.js` to check that prettier formatting has been applied. However, the `lint-staged` config [here](https://github.com/With-the-Ranks/Spoke/blob/311530c44a551b6ee4f3d7fc4cee08138a00d603/package.json#L330) doesn't currently fix json files. Enabling ESLint for json files should ensure we're enforcing consistent formatting pre commit and in CI/CD
N/A
> chore: lint json files

- src/containers/AdminCampaignEdit/index.jsx
- src/containers/AdminCampaignList.jsx
Removes the new=true query parameter from the URL when creating a new campaign, addressing unexpected navigation behavior in the campaign builder.
This change resolves the issue where the new=true query parameter forces admins back to the Basics tab upon saving another section, interrupting the intended flow when filling out sections in any order. See issue [#56](https://github.com/With-the-Ranks/Spoke/issues/56) for details.
Tested by creating a new campaign, navigating between sections, and confirming no forced navigation back to the Basics tab after saving.
The AdminCampaignEdit component still retains the isNew prop, which is currently unused but related to the removed new=true query parameter.
> fix: remove new query parameter when create new campaign

- src/containers/AdminCampaignStats/index.jsx
- src/containers/CampaignList/components/CampaignListRow.tsx
This PR:
1. Fixes a bug with `CampaignListRow` styling introduced in #43 
2. Enables showing the Edit button on the `AdminCampaignStats` age regardless of whether the campaign is archived or not
1. Prevented the archived campaign list from loading
2. Address the annoying problem of not being able to access the campaign editor via the UI for an archived campaign, which prevented easily copying scripts etc. from archived campaigns.
> fix: fix loading of archived campaigns

- .github/workflows/ci-cd.yml
This updates our CI pipeline to accomodate 2025 GitHub deprecations, similar to what we've had to do for other repos
Previous versions deprecated
N/A
> chore(gh): update ci workflow

- .github/workflows/ci-cd.yml
- src/server/api/root-resolvers.ts
This disables MMS file validation temporarily
`@npcz/magic` is throwing an uncatchable exception in dev and in production, whenever an MMS url is used in a script. Until we can investigate further, we should disable MMS file validation, since it's only used for displaying user feedback. This allows users to set up MMS scripts and send MMS while we work on this.
```
{"level":"error","message":"unhandledRejection: Failed to parse URL from /usr/Spoke/node_modules/@npcz/magic/dist/magic-js.wasm","stack":"TypeError: Failed to parse URL from /usr/Spoke/node_modules/@npcz/magic/dist/magic-js.wasm\n    at node:internal/deps/undici/undici:13178:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2025-03-25T19:01:16.343Z"}
```
This has been tested …
> fix(mms): skip file validation

- libs/gql-schema/campaign-contact-tag.ts
- libs/gql-schema/campaign-variable.ts
- libs/gql-schema/campaign.ts
- libs/spoke-codegen/src/graphql/campaign-variables.graphql
- src/api/campaign-variable.ts
- src/containers/AdminCampaignEdit/sections/CampaignCannedResponsesForm/components/CannedResponseEditor.tsx
- src/containers/AdminCampaignEdit/sections/CampaignCannedResponsesForm/components/CannedResponseRow.tsx
- src/containers/AdminCampaignEdit/sections/CampaignCannedResponsesForm/index.tsx
- src/containers/AdminCampaignEdit/sections/CampaignInteractionStepsForm/index.tsx
- src/containers/AdminCampaignEdit/sections/CampaignInteractionStepsForm/resolvers.ts
- src/containers/AdminCampaignEdit/sections/CampaignVariablesForm.tsx
- src/containers/AssignmentTexterContact/components/ApplyTagDialog.tsx
- src/containers/AssignmentTexterContact/index.jsx
- src/containers/TexterTodo/index.jsx
- src/lib/scripts.ts
- src/schema.graphql
- src/server/api/campaign-contact-tag.ts
- src/server/api/campaign-variable.ts
- src/server/api/campaign.js
- src/server/api/lib/campaign.ts
- src/server/tasks/retry-interaction-step.ts
This PR cleans up some typing across a few places:
1. [`CampaignContactTag`](libs/gql-schema/campaign-contact-tag.ts): Removing unused created at and updated at fields for simplified conversion to Tag type where needed
2. [`CampaignVariable`](libs/gql-schema/campaign-variable.ts): Removing unused pagination
3. [`CampaignInput`](libs/gql-schema/campaign.ts): Use arrays of non-optional canned responses and campaign contacts
4. [`campaign.ts`](src/server/api/lib/campaign.ts): misc. typing
Prep for bug fix PR to come
This has been tested locally:
1. Tags - texter, message review (there is an existing bug to fix here
2. Campaign Variables - texter, campaign builder, script preview
3. Campaign Builder - Loading contacts, adding canned responses
> refactor(campaign): simplify subtypes
